# Generated by Django 3.2.8 on 2021-10-28 15:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('QuickFile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('trans', 'Trans')], max_length=10)),
                ('age', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('sodium', models.FloatField()),
                ('potassium', models.FloatField()),
                ('creatinine', models.FloatField()),
                ('urea', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'KFT',
            },
        ),
        migrations.CreateModel(
            name='LFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('trans', 'Trans')], max_length=10)),
                ('age', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('total_bil', models.FloatField()),
                ('direct_bil', models.FloatField()),
                ('alk_phos', models.FloatField()),
                ('gpt', models.FloatField()),
                ('got', models.FloatField()),
                ('ggt', models.FloatField()),
                ('prot', models.FloatField()),
                ('alb', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'LFT',
            },
        ),
        migrations.CreateModel(
            name='Lipid_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('trans', 'Trans')], max_length=10)),
                ('age', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('hdl', models.FloatField()),
                ('trig', models.FloatField()),
                ('total_chol', models.FloatField()),
                ('ldl', models.FloatField(default=0.0, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Lipid Profile',
            },
        ),
        migrations.AlterField(
            model_name='cbc',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('trans', 'Trans')], max_length=10),
        ),
    ]
