# Generated by Django 3.2.8 on 2021-10-28 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuickFile', '0002_auto_20211028_0358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lipid_profile',
            name='ldl',
        ),
    ]
